name: build mesa driver

on:
  workflow_dispatch:

jobs:
  ubuntu:
    runs-on: ubuntu-24.04-arm
    steps:
      - name: get resources and apply patch
        run: |
          echo -e 'deb https://mirrors.tuna.tsinghua.edu.cn/ubuntu-ports/ noble main restricted universe multiverse\ndeb-src https://mirrors.tuna.tsinghua.edu.cn/ubuntu-ports/ noble main restricted universe multiverse\ndeb https://mirrors.tuna.tsinghua.edu.cn/ubuntu-ports/ noble-updates main restricted universe multiverse\ndeb-src https://mirrors.tuna.tsinghua.edu.cn/ubuntu-ports/ noble-updates main restricted universe multiverse\ndeb https://mirrors.tuna.tsinghua.edu.cn/ubuntu-ports/ noble-backports main restricted universe multiverse\ndeb-src https://mirrors.tuna.tsinghua.edu.cn/ubuntu-ports/ noble-backports main restricted universe multiverse\ndeb http://ports.ubuntu.com/ubuntu-ports/ noble-security main restricted universe multiverse\ndeb-src http://ports.ubuntu.com/ubuntu-ports/ noble-security main restricted universe multiverse' | sudo tee /etc/apt/sources.list
          sudo apt update -y
          sudo apt install patchelf ninja-build cmake python3-pip -y         
          pip install mako --break-system-package
          pip install PyYAML --break-system-package
          pip install meson --break-system-package
          sudo apt build-dep mesa -y
          sudo mkdir /data
          sudo chmod 777 /data
          mkdir /data/data/
          mkdir /data/data/com.termux
          mkdir /data/data/com.termux/files/
          mkdir /data/data/com.termux/files/usr
          mkdir /data/data/com.termux/files/usr/glibc
          cd /tmp
          git clone https://github.com/Waim908/mesa_driver_glibc.git patch
          git clone -b mesa-25.1.0 https://gitlab.freedesktop.org/mesa/mesa.git mesa
          . patch/patchelf.sh
          wget -O /tmp/glibc.tar.xz https://github.com/Waim908/lite-termux-glibc/releases/download/nodownload/Lite-glibc-2.41-1.tar.xz 
          tar -xf /tmp/glibc.tar.xz -C /data/data/com.termux/files/usr/
          cd /tmp/mesa
          for i in /tmp/patch/v25/*.patch; do
            echo "应用补丁：$i"
            if ! patch -p1 < "$i" ; then
              echo "$i 应用失败!"
              exit 1
              break
            else
              echo "$i: Done"
            fi
          done
      - name: meson configure
        run: |
          cd /tmp/mesa/
          meson setup builddir -Dprefix=/tmp/glibc -Dbuildtype=release -Dplatforms=x11,wayland -Dgallium-drivers=freedreno,virgl,zink,panfrost,llvmpipe -Dvulkan-drivers=freedreno,panfrost,swrast,virtio -Degl=enabled -Dgles1=disabled -Dgles2=enabled -Dglvnd=enabled -Dglx=dri -Dllvm=enabled -Dgallium-extra-hud=true -Dgallium-va=enabled -Dgallium-vdpau=enabled -Dgbm=enabled -Dvulkan-layers=device-select,overlay -Dfreedreno-kmds=kgsl -Dlibunwind=disabled -Dvalgrind=disabled -Dmicrosoft-clc=disabled
      - name: meson compile & install
        run: |
          cd /tmp/mesa
          meson compile -C builddir && meson install -C builddir
          cd /tmp && cd glibc && patchelf_glibc 
          tar -I 'xz -T$(nproc)' -cvf /tmp/mesa-25.1.0.tar.xz glibc/
      - name: package and release
        uses: softprops/action-gh-release@v2
        with:
          name: test
          draft: false
          prerelease: false
          tag_name: mesa-25.1.0
          body: panfrost turnip llvmpipe virgl virtio
          files: |
            /tmp/mesa-25.1.0.tar.xz
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}